### ISSUE TITLE
More restrictive parsing in current fast_float ?

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rcppfastfloat#4]
Following up on #3 I looked into updating to [fast_float](https://github.com/fastfloat/fast_float) 3.8.2.  There is an immediate issue in that I need to comment-out / alter to `Rcpp::stop()` the line 

https://github.com/fastfloat/fast_float/blob/34d443d6fc1a355e42b215595151c2a45215d6bf/include/fast_float/float_common.h#L84

as R and CRAN cannot allow a naked `abort()`.  Small fries, easy to accomodate upstream.

The bigger issue is that @knapply added some clever examples with leading and trailing whitespace _which all parsed in the previous version_ but no longer do now in the current version.   This wraps the base parser with its error propagation into a canidate replacement `as.double2()`.  The unit test script is short:

```r
library(RcppFastFloat)

set.seed(8675309)
input <- sample(c(
  paste0(" \r\n\t\f\v", c(0.0, sqrt(seq(1, 10))), " \r\n\t\f\v"),
  c("NaN", "-NaN", "nan", "-nan",
    "Inf", "-Inf", "inf", "-inf", "infinity", "-infinity",
    NA_character_,
    "  1970-01-01", "1970-01-02  ")
))

expect_equal(suppressWarnings(as.double(input)),
             suppressWarnings(as.double2(input)))
```

The input is 

```
> input
 [1] "infinity"                               " \r\n\t\f\v3.16227766016838 \r\n\t\f\v"
 [3] " \r\n\t\f\v3 \r\n\t\f\v"                "  1970-01-01"                          
 [5] "-NaN"                                   "-inf"                                  
 [7] " \r\n\t\f\v2.82842712474619 \r\n\t\f\v" "nan"                                   
 [9] " \r\n\t\f\v2.44948974278318 \r\n\t\f\v" "Inf"                                   
[11] " \r\n\t\f\v2 \r\n\t\f\v"                "-infinity"                             
[13] " \r\n\t\f\v0 \r\n\t\f\v"                " \r\n\t\f\v1.73205080756888 \r\n\t\f\v"
[15] " \r\n\t\f\v1 \r\n\t\f\v"                " \r\n\t\f\v1.4142135623731 \r\n\t\f\v" 
[17] " \r\n\t\f\v2.23606797749979 \r\n\t\f\v" "1970-01-02  "                          
[19] " \r\n\t\f\v2.64575131106459 \r\n\t\f\v" "inf"                                   
[21] "-nan"                                   "NaN"                                   
[23] NA                                       "-Inf"                                  
> 
```

and under current `fast_float` it goes belly-up:

```r
> suppressWarnings(as.double2(input))
 [1]  Inf   NA   NA   NA  NaN -Inf   NA  NaN   NA  Inf   NA -Inf   NA   NA   NA   NA   NA
[18]   NA   NA  Inf  NaN  NaN   NA -Inf
> 
```

whereas under the previous version we get the same as with R's own `as.double()`:

```r
> suppressWarnings(as.double2(input))
 [1]     Inf 3.16228 3.00000      NA     NaN    -Inf 2.82843     NaN 2.44949     Inf
[11] 2.00000    -Inf 0.00000 1.73205 1.00000 1.41421 2.23607      NA 2.64575     Inf
[21]     NaN     NaN      NA    -Inf
> suppressWarnings(as.double(input))
 [1]     Inf 3.16228 3.00000      NA     NaN    -Inf 2.82843     NaN 2.44949     Inf
[11] 2.00000    -Inf 0.00000 1.73205 1.00000 1.41421 2.23607      NA 2.64575     Inf
[21]     NaN     NaN      NA    -Inf
> 
```

@lemire Is there an 'obvious' toggle I should add to skip non-numeric pre/post content?  Otherwise, I will have to treat this as a regression and not update to 3.8.2.

**Comment by lemire** [comment]
I will be removing FASTFLOAT_ASSERT. 

> Is there an 'obvious' toggle I should add to skip non-numeric pre/post content? Otherwise, I will have to treat this as a regression and not update to 3.8.2.

It is a deliberate change...

https://github.com/fastfloat/fast_float/pull/64

I will add it back with a MACRO (disabled by default).

**Comment by eddelbuettel** [comment]
Thank you for the pointer!  I will peruse -- this sounds like a case where I should just align the unit tests (and documentation example) to the new behavior.   Don't rush re-enabling it yet.

**Comment by eddelbuettel** [comment]
Maybe I am dense but the exclusion of something like `+` (because C++17 also does it) should not affect the change from  parsing `" \r\n\t\f\v3.16227766016838 \r\n\t\f\v"` to no longer parsing it.

Do I have it right that [fast_float PR #64](https://github.com/fastfloat/fast_float/pull/64/files) deals with leading `+` ?  We see a much larger delta in behaviour here.  Not necessarily one we need, but it so happens that we _tested_ for it ...

**Comment by eddelbuettel** [comment]
I think I can live with removing `\r\n\t\f\v` from the tests on my end.

**Comment by lemire** [comment]
@eddelbuettel It is fine, I can do it for you.

**Comment by lemire** [comment]
Give me a minute, I need to build a test.

**Comment by eddelbuettel** [comment]
That was all @knapply so I am right now not exactly sure what motivated it ... and/or how much it is needed.  I can simplify the unit tests comparison file against R's own `as.double()` to this 

```r
library(RcppFastFloat)

set.seed(8675309)
input <- sample(c(
  paste0(c(0.0, sqrt(seq(1, 10)))),
  c("NaN", "-NaN", "nan", "-nan",
    "Inf", "-Inf", "inf", "-inf", "infinity", "-infinity",
    NA_character_,
    "  1970-01-01", "1970-01-02  ")
))

expect_equal(suppressWarnings(as.double(input)),
             suppressWarnings(as.double2(input)))
```

**Comment by lemire** [comment]
I will craft something and we can see if it addresses your concerns. I expect it will.

**Comment by eddelbuettel** [comment]
Can you also spend maybe a second on thinking how to not embed `abort()` unconditionally?  I will always have to edit that out as R checks the generated object code for symbols it does not like: `abort()` (which would take the session down), `exit()` (ditto), `printf()` (should use R's i/o stream), `cout` (ditto) and so on.

**Comment by lemire** [comment]
Can you review this PR? If it meets your needs, I will quickly issue a release.

https://github.com/fastfloat/fast_float/pull/170

I actually missed the introduction of the abort() while doing code review. I would not have accepted it. I use abort() in tests or in development mode, but I don't want to release code with abort() when I can avoid it. Sorry.

Just ping me here or at the PR once you approve.

I have not checked rcppfastfloat, but to my knowledge, we never checked for trailing content. So I want `1970-12` to parse to 1970 and bring me to `-`, but, of course, if you don't want that, you check just start from where the number parsing ended and check for non-desired content:  https://github.com/fastfloat/fast_float/pull/170/files

**Comment by eddelbuettel** [comment]
Files synced, thanks for the quick turnaround and the `abort()` cleanup.  Now, for the new one do you recommend I define `FASTFLOAT_SKIP_WHITE_SPACE` and/or `FASTFLOAT_ALLOWS_LEADING_PLUS`?  I guess I'd need the former?

**Comment by lemire** [comment]
Right so you could do...

```
#define FASTFLOAT_SKIP_WHITE_SPACE 1
#define FASTFLOAT_ALLOWS_LEADING_PLUS 1
```

before the include. Of course, you could also skip white space yourself if you'd like, then you don't need any macro.

**Comment by eddelbuettel** [comment]
Schwwwweeeeetttt.  If use

```c++
#define FASTFLOAT_SKIP_WHITE_SPACE 1
#include "fast_float/fast_float.h"
```

in the file defining `as_dbl` (which we export as `as.double2()`) then all is well.   We weren't using the leading plus but I can throw it in...

**Comment by lemire** [comment]
Ok. I am releasing.

**Comment by eddelbuettel** [comment]
I had sync'ed, but not yet committed / pushed, at my end.  I'll do that once I see the new version.

**Comment by lemire** [comment]
https://github.com/fastfloat/fast_float/releases/tag/v3.9.0

**Comment by lemire** [comment]
https://github.com/fastfloat/fast_float/releases/download/v3.9.0/fastfloat.h

**Comment by eddelbuettel** [comment]
Thank you!  (And I still using the 'per directory' approach:  https://github.com/eddelbuettel/rcppfastfloat/tree/master/inst/include/fast_float  (and all that is pre-merge -- work is currently in a branch here....)

**Comment by eddelbuettel** [comment]
Now all done in branch https://github.com/eddelbuettel/rcppfastfloat/tree/feature/updated_upstream which will be in `master` as a release 0.0.4 'shortly'.  Big thank you to @lemire for speedy-as-usual replies.  Much appreciated.
